- include_tasks: "../roles/common/tasks/run_airflow_container.yml"
  vars:
    container_name: "{{ inventory_hostname }}"
    command: celery worker -q default,"{{ inventory_hostname }}"
    restart_policy: always
    hostname: "{{ inventory_hostname }}"
    var_exposed_ports:
      - 8793
    ports:
      - 8793:8793

- name: restart workers
  shell: docker restart $(docker ps --filter "name=worker" -q)4


### dbt ###
- name: create dbt directory
  file:
    path: "{{ airflow.airflow_host_dir }}/dbt/"
    state: directory
    mode: 0777
