- include_tasks: "../roles/common/tasks/run_airflow_container.yml"
  vars:
    container_name: "{{ inventory_hostname }}"
    command: celery worker
    restart_policy: always
    hostname: "{{ inventory_hostname }}"
    var_exposed_ports:
      - 8793
    ports:
      - 8793:8793
