- name: "01 - airflow - run container - {{ command }}"
  docker_container:
    name: "airflow_{{ container_name if container_name is defined else command | replace(' ', '_') }}"
    image: "apache/airflow:2.5.1-python3.8"  #  path to the docker registry (nexus?)
    state: started
    pull: yes
    docker_api_version: auto
    command: "{{ command }} "
    restart_policy: "{{ restart_policy | default('no') }}"
    ports: "{{ ports | default([]) }}"
    hostname: "{{ hostname | default('') }}"
    etc_hosts: "{{ extra_hosts | default({}) }}"
    exposed_ports: "{{ var_exposed_ports | default([]) }}"
    user: airflow
    volumes:
     - "{{ airflow.airflow_host_dir }}/airflow/logs:/opt/airflow/logs"
     - "{{ airflow.airflow_host_dir }}/airflow/dags:/opt/airflow/dags"
     - "{{ airflow.airflow_host_dir }}/airflow/plugins:/opt/airflow/plugins"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "{{ airflow.airflow_host_dir }}/dbt:/opt/dbt" # dir for dbt projetcs
    env_file: "{{ airflow.airflow_host_dir }}/airflow/airflow.env"
    auto_remove: "{{ auto_remove | default('no') }}"