---
- name: config hosts
  hosts: "*"
  roles:
    - role: "common"
      vars:
        config: "{{ airflow }}"

- name: start airflow workers
  hosts: "workers_group_1"
  roles:
    - role: "workers"
      vars:
        workers: "{{ airflow.workers_groups['workers_group_1'].workers }}"
        worker_group: workers_group_1

- name: start airflow servers
  hosts: "servers"
  roles:
      - role: "servers"
        vars:
          config: "{{ airflow }}"
