---
- name: config hosts
  hosts: "*"
  roles:
    - role: "common"
      vars:
        config: "{{ airflow }}"

- name: start airflow workers
  hosts: "workers"
  roles:
    - role: "workers"

- name: start airflow servers
  hosts: "servers"
  roles:
      - role: "servers"
        vars:
          config: "{{ airflow }}"