---
- name: config hosts
  hosts: "*"
  roles:
    - role: "common"

- name: start airflow workers
  hosts: "workers"
  roles:
    - role: "workers"

- name: start airflow servers
  hosts: "servers"
  roles:
      - role: "servers"
